  @echo off
  echo Сброс настроек Winsock...
  netsh winsock reset
  echo Сброс IP настроек...
  netsh int ip reset
  echo Очистка кэша DNS...
  ipconfig /flushdns
  echo Сброс настроек брандмауэра...
  netsh advfirewall reset
  echo Сброс настроек завершен. Перезагрузите компьютер для применения изменений.
  pause
